### ISSUE TITLE
Validate color from System.Drawing.ColorTranslator.FromHtml

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#1]
This:

````csharp
System.Drawing.ColorTranslator.FromHtml("wrong color");
````

Will be marked as an `Error`. Category is `Usage`.
Diagnostic id is `CC0053`

How to implement it is being discussed below, we still have to find an optimal way to do it, as we cannot call `ColorTranslator` from the Code Cracker project and see if it throws, as CC is a PCL, and `System.Drawing` is not available.

@dgmachado is working on it.

**Comment by dgmachado** [comment]
Ok, it's my first PR in this project. I'll try do this. Could you assign it to me?

**Comment by giggio** [comment]
@dgmachado It is yours. I have invited you to the collaborators team, when you accept I will be able to assign it you. You can already start.

**Comment by giggio** [comment]
@dgmachado BTW, there was a lot being dicussed in this thread. Please read the whole thing and if you have any questions let us know.

**Comment by dgmachado** [comment]
My idea would be don't show any code fixes for the analyzer. We simply validate the color and offer no code fix just a message error if there is a error on parsing. 

**Scenario 1 -  Valid data types input:**
Obs: Analyzer does not create diagnostic
``` 
namespace ConsoleApplication
            {
                class TypeName
                {
                    public int Foo()
                    {
                        ColorTranslator.FromHtml("");
                        ColorTranslator.FromHtml("#FFFFFF");
                        ColorTranslator.FromHtml("Red");
                        ColorTranslator.FromHtml("200");
                        ColorTranslator.FromHtml("200;100;50");
                        ColorTranslator.FromHtml("200;100;50;60");
                    }
                }
            };
```

**Scenario 2 -  Invalid data types input:**
Obs: Analyzer creates diagnostic
``` 
namespace ConsoleApplication
            {
                class TypeName
                {
                    public int Foo()
                    {
                        ColorTranslator.FromHtml("#FFFZZZ");
                        ColorTranslator.FromHtml("bluee");
                        ColorTranslator.FromHtml("200;100");
                        ColorTranslator.FromHtml("200;JJ;50;60");
                        ColorTranslator.FromHtml("200;100;50;100;60");
                    }
                }
            };
```



**Scenario 3 - Ignore validation for not literal expression syntax:**
Obs: Analyzer does not create diagnostic
``` 
namespace ConsoleApplication
            {
                class TypeName
                {
                    public int Foo()
                    {
                        var htmlColor = "#FFFFFF";  
                        ColorTranslator.FromHtml(htmlColor);
                    }
                }
            };
```




---- 
What do you think about all this?

**Comment by dgmachado** [comment]
Only to justify why I don't think that we should include include a code fix for suggest substitute the parameter "#FFF" to Color.White like some opinions above. We have so many valid data types input, why choose just this one? And if we decide to do it I think that would be a new one analyzer marked as an warning and category style. What do you think?

**Comment by giggio** [comment]
This analyzer will not have a corresponding fix. It is just like the Uri analyzer, and the regex analyzer.

**Comment by giggio** [comment]
And I am fine with the test cases you created. They seem correct.

**Comment by giggio** [comment]
Closed on #446.

**Comment by thomaslevesque** [comment]
Some of the tests for this analyzer are failing on a system with French as the current culture. A color like `"200, 200, 200"` is valid in English, but not in French, because the list separator in French is `;`, no `,`. The analyzer can't rely on the `CurrentCulture` as it currently does, because it doesn't know which culture will be in use when the code runs.

Actually, the `ColorTranslator` class from System.Drawing has the same issue. So I don't think it's possible to make a reliable analysis for this color syntax. You can't ensure that `ColorTranslator.FromHtml` will succeed, because it depends on the runtime culture (also, the method doesn't have an overload that takes a `CultureInfo`, so there is no way to force the invariant culture).

IMO the best course is to not attempt to actually validate colors with this syntax, but instead warn that it is culture dependent, and suggest using `ColorConverter` instead (which does accept a `CultureInfo`).

**Comment by giggio** [comment]
@thomaslevesque We have a way to make this work, we can use the `ChangeCulture` class to help with that. Can you try to add this to these tests that are breaking? I cannot do it, because my environment is all en-us.

**Comment by thomaslevesque** [comment]
@giggio, this will fix the test, but not the underlying problem, which is that code like `ColorTranslator.FromHtml("200, 200, 200")` is _never_ safe, since it will only work in some cultures. So in this case the analyzer should always emit a diagnostic, even if the color string is valid in the current culture.

(color strings like "#C8C8C8", on the other hand, are always safe)

**Comment by giggio** [comment]
@thomaslevesque Ok, 2 things, then:

1. Can you submit a PR with the `ChangeCulture` points where that is currently failing for you, so it does not fail anymore?
2. Should we create an analyzer and code fix that changes from one API to another?

**Comment by thomaslevesque** [comment]
> Can you submit a PR with the ChangeCulture points where that is currently failing for you, so it does not fail anymore?

Actually, `ChangeCulture` is already used in that test. But it only changes the culture for the current thread, and since the code is asynchronous, it doesn't stay on the same thread... When it gets to the point where the color is parsed, the culture is back to the system default.

According to [this](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo%28v=vs.110%29.aspx#Async), the current culture is now part of the async operation context for apps that target .NET 4.6. But I tried to retarget the tests projects to 4.6, and it doesn't change anything.

Still looking into it...

> Should we create an analyzer and code fix that changes from one API to another?

I was thinking of just updating the current analyzer, if possible

**Comment by thomaslevesque** [comment]
I think the problem is that even though the unit test project targets 4.6, the executable that runs the test doesn't, so the new behavior is not used...

**Comment by thomaslevesque** [comment]
I was able to make it work (see #584).

Anyway, this fixes the tests, but not the underlying problem...
