### ISSUE TITLE
Remove private method is never used in a class

### ISSUE THREAD

**Issue by julianosaless** [code-cracker/code-cracker#204]
Remove private method is never used in a class.
This example, analizer will remove privete method  "ConfigureFoo()" never used  in class

This source:

    public class Foo
    {
        public void GetFoo()
        {
            
        }

        public void SetFoo()
        {
            
        }

        private void ConfigureFoo()
        {
            
        }
    }

Became:

    public class Foo
    {
        public void GetFoo()
        {
            
        }

        public void SetFoo()
        {
            
        }

    }

Severity: Info
Category: Using
Diagnostic id: CC0068

**Comment by carloscds** [comment]
@julianosaless  Remove ou comment ?

**Comment by julianosaless** [comment]
@carloscds I think that  remove is better, what do you think ?

**Comment by viniciushana** [comment]
I'd go for removing. Version control systems are there for this kind of thing in case the method needs to  be brought back!

**Comment by carloscds** [comment]
@julianosaless Go ahead!

**Comment by ElemarJR** [comment]
If you comment, an analyzer that I wrote sometime ago will recommend you to remove.

**Comment by julianosaless** [comment]
I'll develop this issue, Thank you all so much :) 
@working

**Comment by giggio** [comment]
Guys, this is not `Ready` yet. We need diagnostic Id, category, severity and a significant test case on the description. @julianosaless can you add it, please?

**Comment by julianosaless** [comment]
@giggio  I updated a issue :)

**Comment by giggio** [comment]
@julianosaless I don't think this is `Style`. Maybe `Using`?
And `CC0063` is taken. See the diagnostics table: https://github.com/code-cracker/code-cracker/wiki/DiagnosticIds
You can grab a number there and update the table.

**Comment by julianosaless** [comment]
@giggio, thanks for tips,I agree with you, "Using" is better that "Style"

**Comment by jwooley** [comment]
In some of the  base class discussions on the VB port, we found that it might make sense to have the ID’s managed in a single static class as consts so that they can be accessed globally from the Analyzer,  CodeFix, and Unit Test without the need to imbed it in each analyzer separately. See issue 214 https://github.com/code-cracker/code-cracker/issues/214






Sent from Windows Mail





From: Giovanni Bassi
Sent: ‎Monday‎, ‎January‎ ‎12‎, ‎2015 ‎2‎:‎40‎ ‎PM
To: 'code-cracker/code-cracker'





@julianosaless I don't think this is Style. Maybe Using?
And CC0063 is taken. See the diagnostics table: https://github.com/code-cracker/code-cracker/wiki/DiagnosticIds
You can grab a number there and update the table.

**Comment by giggio** [comment]
@julianosaless How is this coming? Are you still going to work on it?

**Comment by julianosaless** [comment]
@gigio,  I am worked, some things happened  this month, but  i believe that
next saturday i will finish this issue.

2015-02-04 2:44 GMT-02:00 Giovanni Bassi <notifications@github.com>:

> @julianosaless <https://github.com/julianosaless> How is this coming? Are
> you still going to work on it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-cracker/code-cracker/issues/204#issuecomment-72789946>
> .
>



-- 
Juliano Sales
Software Developer
http://juliano-sales.net

**Comment by giggio** [comment]
Closed on #274, a bug is pending on #276.
