### ISSUE TITLE
Is it possible to generate an output xml file?

### ISSUE THREAD

**Issue by laedit** [code-cracker/code-cracker#269]
Hi,

Sorry to add another issue, this is more a question.
Is it possible to generate an xml file with the code analysis result?
If not do you plan to propose it?

Thanks.

**Comment by giggio** [comment]
This is more of an msbuild thing. Maybe there is a way already. I am not sure.

**Comment by tmeschter** [comment]
@laedit This is more of an issue for https://github.com/dotnet/roslyn. Individual analyzers shouldn't write data to disk (since they have little knowledge or control over the build environment). Instead, that would need to be done by csc.exe/vbc.exe.

Could you open an issue over there and describe what kind of information you would want in such a file?

**Comment by laedit** [comment]
@tmeschter thanks for the tip, I will do that.

**Comment by giggio** [comment]
@tmeschter agreed.
@laedit I will close this issue, as it seems that the Roslyn team will pick it up on https://github.com/dotnet/roslyn/issues/430
