### ISSUE TITLE
Visual studio crash on initializer refactoring (CC0009)

### ISSUE THREAD

**Issue by thorgeirk11** [code-cracker/code-cracker#315]
Visual studio crashes on the following code.

```CSharp
class Point
{
    public int X { get; set; }
    public int Y { get; set; }
}
Point GetPoint() { return null; }

Point myPoint;
void Foo()
{
    myPoint = GetPoint();
    myPoint.X = 5;
}
```

![image](https://cloud.githubusercontent.com/assets/2693474/7217741/f455a6d4-e631-11e4-85be-a3d7f24f3ad3.png)

When I try to see the code fix VS crashes.

**Comment by giggio** [comment]
I have reproduced it. The error is happening at line 56 of the code fix provider.

https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Style/ObjectInitializerCodeFixProvider.cs#L56

````csharp
var objectCreationExpression = statement.DescendantNodes().OfType<ObjectCreationExpressionSyntax>().Single();
````

A diagnostic should not be raised for this situation, the code fix is correct, the problem is at the analyzer.

**Comment by giggio** [comment]
Done on #316, just let's wait for the merge.
