### ISSUE TITLE
Remove virtual modifier if possible

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#371]
** It should apply to all member that can be made virtual. **

This is an example only. This:

````csharp
class C
{
    public virtual void Foo() { }
}
````

Becomes:

````csharp
class C
{
    public void Foo() { }
}
````

An analysis has to be made if the method can me made virtual. The analyzer has to check if there is derived class, and if in those classes if there is an override of the method.

Category: `Performance`
Diagnostic Id: `CC0093`
Severity: `Warning`

**Comment by giggio** [comment]
There is a problem in this analyzer, as we need to check on compilation end only if there are derived classes. I am not sure the analyzer is worth it and we already have other issues blocked because of this.

**Comment by adraut** [comment]
This would be really annoying for creating libraries.  It is very common to mark methods and properties as virtual if even they are never overridden in your own library.  This would be really annoying when using things like Entity Framework since it's required to mark properties virtual for relations, but the method isn't overridden until runtime when the proxy is generated.  In my opinion this would probably be high on the list of most often disabled analyzers.

**Comment by giggio** [comment]
That is fine. We might even deliver it disabled, then.

**Comment by giggio** [comment]
For me, the main problem is the one I stated on the 1st comment: it would be really hard to run, and we are already having problem with other analyzers that analyze in a similar way (using compilation end). See #293.

**Comment by giggio** [comment]
I am closing this issue because of the problems stated on #293.
