### ISSUE TITLE
C# - insert auto comment when close brackets

### ISSUE THREAD

**Issue by midnait** [code-cracker/code-cracker#635]
Hi CC Team

In VB, just to look at the code and you already know where the end blocks. In C#, depending on the amount of braces, you must pass the mouse over each brace to make sure what is the end of the block.

I believe that a auto comment option would be useful to facilitate the reading of the code and its maintenance:

     } // end if(...
    } // end foreach(entities...
   } // end using(dbcontext...
  } // end void routine

To avoid pollution visual, the auto comment will do your work only when the open brace is far away, maybe 20 rows of distance, configurable.

Thanks for your time, and sorry my poor english.

**Comment by carloscds** [comment]
@midnait Do you know this plugin: https://visualstudiogallery.msdn.microsoft.com/e792686d-542b-474a-8c55-630980e72c30 Maybe can help you with this.

**Comment by midnait** [comment]
@carloscds tks, but this dont avoid rolling up screen or move mouse over }

**Comment by carloscds** [comment]
@midnait Sorry for confusion, the correct plugin is Productivity PowerTools: http://blogs.msdn.com/b/visualstudio/archive/2013/12/19/productivity-power-tools-for-visual-studio-2013.aspx
It has a funcionality that when you put your mouse over '}' show begin of block.

**Comment by jwooley** [comment]
Personally, I hate the use of comments here. It screams that the code should have been refactored into smaller more manageable chunks, much in the same way that regions are an anti-pattern to many. IF we have to provide this refactoring, I would recommend one that does the opposite - remove trailing comment trivia from end brackets.

**Comment by giggio** [comment]
I also don't like it, because it changes the code. And because if you change the condition for the if, for example, it will not automatically change the comment, we would have to run it again. If there is another extension that solves the problem without changing the code, and it's there as Carlos pointed out, I would prefer it.
I agree with Jim that such code is screaming for a refactoring, but these codes exist, and maybe we can help. I just don't think an analyzer is the best way to solve this problem. After dwelling on this idea for a while, I believe we should not do it.

**Comment by carloscds** [comment]
@giggio @jwooley Visual Studio Productivity Tools has this functionality. My suggest is close this issue.
