### ISSUE TITLE
AD0001 Crash

### ISSUE THREAD

**Issue by noah80** [code-cracker/code-cracker#638]
I keep getting the crash below. Any ideas?

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'CodeCracker.CSharp.Usage.DisposableFieldNotDisposedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	DatabaseIO		1	Active	Analyzer 'CodeCracker.CSharp.Usage.DisposableFieldNotDisposedAnalyzer' threw the following exception:
'System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeCracker.CSharp.Usage.DisposableFieldNotDisposedAnalyzer.CallsDisposeOnField(IFieldSymbol fieldSymbol, MethodDeclarationSyntax disposeMethod, SemanticModel semanticModel)
   at CodeCracker.CSharp.Usage.DisposableFieldNotDisposedAnalyzer.ContainingTypeImplementsIDisposableAndCallsItOnTheField(SymbolAnalysisContext context, IFieldSymbol fieldSymbol, INamedTypeSymbol typeSymbol)
   at CodeCracker.CSharp.Usage.DisposableFieldNotDisposedAnalyzer.AnalyzeField(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass33_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by giggio** [comment]
@noah80 Are you able to pinpoint exactly what code is producing the bug?

**Comment by noah80** [comment]
Unfortunately not. The message is all I get in the error window of VS. 

Trying to debug extensions seems to be a rather non-enjoyable process too, and I haven't had time to experiment with that. 

Could you maybe add a try/catch block which prints the location of the code? I'll post the culprit code then.  And adding some errorhandling for more graceful failing might be good anyway for the stability, no?

**Comment by jwooley** [comment]
@noah80 Are you using VS 2015 Update1? We've found that this typically only surfaces with Update1 which has a newer (1.1) version of the Microsoft.Analyzer libraries. At this point, CC is still targeting the 1.0 version to ensure compatibility with VS 2015 without update 1.

Also, which version of CC are you using? If you could, see if you can try building CC from source and using that library instead of the one from Nuget. We have pushed in a change that fixes at least one of these errors, but I don't think it addressed issues in DisposableFieldNotDisposedAnalyzer. 

It is tricky debugging these errors. Is it possible to access your source to test against? Alternatively, you could grab the source of CC and F5 debug it. When the experimental version of VS opens, open your erroring project and see if you can catch the exception in the debugger of the copy of VS running CC. That should at least give an indication of the class and method that are causing the error to help identify a repro scenario.

**Comment by carloscds** [comment]
@noah80 Do you test @jwooley solution ?
