### ISSUE TITLE
CC0016 and CC0031 are doing similar work

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#662]
This code will raise both `CC0016` and `CC031`:

````csharp
class Foo
{
    Action a = () => { };
    public void Bar()
    {
        a();
    }
}
````

With:

````
Warning	CC0031	Use ?.Invoke operator and method to call on 'a' delegate.
Warning	CC0016	Copy the 'a' event to a variable before firing it.
````

It seems redundant.
Also, if you fix it with either one of their suggested fixes, both go away. Another evidence that they are doing similar work.

We need to decide if we should maybe reduce the scope on one of them.

**Comment by Vossekop** [comment]
So I just finished working on both of them, and besides some trouble with unit tests the fix for CC0031 was so similar to CC0016 that I tend to agree with this. They could be merged, but in that case the message should change to something that tells the whole story. Also the null check is now not present in CC0016, just the check for the call being performed on a local variable.

**Comment by wmjordan** [comment]
The following code should not trigger CC0031, but it did in the current release.

````csharp
public static void Get(Func<int,int> method) {
    return method != null ? method(12345) : 0;
}
````

**Comment by giggio** [comment]
@wmjordan issue #779 created for this situation. When you find a bug, you can just open an issue, it is better than commenting on a closed one like this, it could go without us noticing it.
And thanks for another bug report!
