### ISSUE TITLE
CC0022 when theer is ternary operator in using

### ISSUE THREAD

**Issue by DzonnyDZ** [code-cracker/code-cracker#665]
Following code generates CC0022
```C#
using (color.HasValue ? new ConsoleColorContext(color.Value) : null)
```
and when I click on "Show potential fixes" DisposableVariableNotDisposedCodeFixProvider crashes

**Comment by giggio** [comment]
Bug confirmed. Here is the test case:

````csharp
struct ConsoleColorContext : IDisposable
{
    public void Dispose()
    {
        throw new NotImplementedException();
    }
}

void Foo()
{
    ConsoleColorContext? color = null;
    using (color.HasValue ? new ConsoleColorContext(color.Value) : null)
    {
    }
}
````

The code fix is crashing and the analyzer should not generate a diagnostic.

**Comment by martinzimmermann** [comment]
I had a look at this bug and I couldn’t reproduce it with your code, the code 
```CSharp
using System;
namespace CSharpNamespace
{
    public class CSharpClass
    {
        struct ConsoleColorContext : IDisposable
        {
            public void Dispose()
            {
                throw new NotImplementedException();
            }
        }
 
        void Foo()
        {
            ConsoleColorContext? color = null;
            using (color.HasValue ? new ConsoleColorContext (color.Value) : null)
            {
            }
        }
    }
}
```
on the other hand, also produces the bug for me. 
I think this is because of an unrelated “bug”. The important part is the `using System;`. When you include `using System;` in your code and use the SemanticModel for getting Symbol information on ConsoleColorContext you get the “System.IDisposable” type. If you do not include `using System;` in your code you only get “IDisposable”. 
On https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Usage/DisposableVariableNotDisposedAnalyzer.cs#L51
There is a comparison with hard coded string “System.IDisposable”, which depending on whether it is “IDisposable” or “System.IDisposable” continues the Analyzer. 

Should we consider this a bug? 
Are there other places, where the including of usings could have an impact on test results?

Also I want to grab this issue, if it is ok.
