### ISSUE TITLE
CC0120: Suggest default for switch statements (C#)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#780]
A lot of bugs are caused by non-exhaustive matching in switch statements.
If there is no default case one should be added that throws an exception.

Before:

``` csharp
switch (a)
{
    case "":
        break;
}
```

After:

``` csharp
switch (a)
{
    case "":
        break;
    default:
        throw new Exception("Unexpected Case");
}
```

Should not raise for `boolean` if `true` and `false` are already handled:

``` csharp
var f = true;
switch (f)
{
    case true:
        break;
    case false:
        break;
    default:
        break;
}
```

Should not raise a diagnostic if [CS0151](https://msdn.microsoft.com/en-us/library/dh0x1stb.aspx)(C# A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type) is already raised in the switch.

Diagnostic Id: `CC0120`
Category: `Design`
Severity: `Warning`

Same as #767, but for C#.

@cezarant is working on it.

**Comment by cezarant** [comment]
Hi @giggio i'm newbie in CodeCracker. I would like to contribute to the project.  This task seems to be interesting to start. I Cloned the project, created a local branch, updated all the dependencies and i am ready to start studying how the analyzer works. Is there any other required step, so I can start contributing?

**Comment by carloscds** [comment]
@cezarant Go ahead and welcome!

**Comment by cezarant** [comment]
I'm having trouble compiling the project. MSBuild works ok. But the dll's generated not bring my modifications. Any suggestions @giggio  @carloscds ?  
I'm using Visual Studio Comunitty in Windows 10.

**Comment by jwooley** [comment]
@cezarant How are you trying to consume this? Are you trying to test/debug your fixes or trying to build and use your private build versions in existing projects? From a test/debug scenario, I would recommend either creating unit tests (which are required to push changes anyway) as a first option and secondly to set VS with the code cracker source to debug into the experimental hive version of vs with your project loaded. 

If you are just trying to consume your private builds, you should be able to build the dll and add the reference to that version rather than your local one. Make sure to uninstall code cracker if you got it online otherwise first to make sure you don't run into version conflicts.

**Comment by cezarant** [comment]
Hi @jwooley i trying to test/debug my fixes in order to participate this issue.

I'm try to understand how the Roslyn works and try build an code Analyser, as explained [here](http://elemarjr.com/pt/2014/11/15/codecracker-parte-2-construindo-um-analyzer/) by Elemar 

To "put the foot in the water", my steps were as follows: 

1 - Install code cracker by nuget , do some tests to know the project work and uninstall.
2 - Fork the project, clone in my machine, create an local branch and restore dependencies. 
3 - Build the project using Msbuild, how indicated in the readme.

From there , I imagined to follow the steps in this [video](https://www.youtube.com/watch?v=06gAoqKd9RA ), from the minute 57:18. 

- Copied an existing analyzer and create a new analyzer. (ex: SwitchCaseAnalyzer in Design Folder) 
- Created a test (SwitchCaseTest) and a CodeFix (SwitchCaseCodeFix)
- Created a value in the enumeration Diagnostic Id,with the suggested number in the title of this issue: switchCaseWithoutDefault:0120. 

By intuition , I believed that when I compile the project , the dll would fetch the my test analyser.
But, my analyzer not appear on the dll that was compiled. C:\CodeCracker\code-cracker\src\CSharp\CodeCracker\bin\Debug\CodeCracker.CSharp.dll
![catch2](https://cloud.githubusercontent.com/assets/1169761/15269988/d424af4c-19e6-11e6-9ae3-36624abf3193.png)

**Comment by jwooley** [comment]
The DLL you generate will be used by the unit test project, but is not used when debugging the currently running visual studio because if you stop on a breakpoint within the current process, VS won't be able to step into your code (responding to F11) because VS itself is in a break process. Instead, if you want to debug outside of unit tests, set the vsix project as your startup project. When you F5 debug, it will load a sandboxed second instance of VS where you can load a sample project and test your code in the IDE (with breakpoints and other standard debugging environments). 

Note that F5 debugging is significantly slower than using the unit tests for debugging purposes, but is sometimes necessary to find which edge cases you didn't anticipate (and need to add to your unit tests).

**Comment by cezarant** [comment]
Thank you! @jwooley I am progressing here...  :)

**Comment by cezarant** [comment]
Hi devs! How i create an switcase expression with an empty string? 
Something like:  
`var label = SyntaxFactory.CaseSwitchLabel("string.empty");`

**Comment by carloscds** [comment]
@cezarant Look at this site: http://roslynquoter.azurewebsites.net/ It's a tool to show syntax tree.

**Comment by cezarant** [comment]
Hi Devs! 
Built the analyzer and codeFixer for this issue. The id is SwicthWithoutDefault. Also built four tests, for the following:  

1- Using a Boolean variable 
2- With the default clause already inserted 
3- With the compilation error CS0151
4- Without the Default clause

I merge locally and I'm ready to do the pull request. 
Are there any step that I can perform the pull request?
