### ISSUE TITLE
Make a variable const whenever it's possible

### ISSUE THREAD

**Issue by ElemarJR** [code-cracker/code-cracker#79]
``` csharp
class Foo
{
    void MyMethod()
    {
        int i = 0;
        Console.WriteLine(i);
    }
};
```

Becomes

``` csharp
class Foo
{
    void MyMethod()
    {
        const int i = 0;
        Console.WriteLine(i);
    }
};
```

This is an `Info`.
Diagnostic id `CC0030`.

**Comment by kwhitefoot** [comment]
I think that it would be useful if this diagnostic also checked to see if the variable was actually used anywhere other than where it is declared.  I'm finding that it is a useful diagnostic for finding unused variables in VB but it is slower than it should be because I have to apply the fix first and then VS itself finds that it is unused.

**Comment by giggio** [comment]
@kwhitefoot it should only raise the diagnostic if the variable is unused. If you have a scenario where, after the fix is applied, the code breaks, it is a bug. Please report it so we can check it out.

**Comment by kwhitefoot** [comment]
I don't think I made my point clearly.  The diagnostic correctly discovers that the variable can be declared Const in stead of Dim.  So I apply the fix.  It is correct, nothing is broken.  But now I discover, or rather the compiler discovers, that the constant is actually unused.  So now I delete it.

So I was wondering if the diagnostic could look ahead to see if the variable is actually used anywhere and offer a fix that simply deletes it instead of converting it into a Const.  

It could be that this only applies to VB and not to C#.

**Comment by giggio** [comment]
@kwhitefoot Interesting. And the compiler only reports that there are no uses for consts, but not when declared with `Dim`?
We could evolve the code fix to do that, both for VB and C#.
